Vreco – Fortran Program
Vreco Program
576 statements
Source File
Uses:
omp_lib
kinds
pot_data
  iz=iz+1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Calls
Variables
v sp la vmax maxw minw ed cube_tmp cube_rad norm_proj v_proj i j k l iii ios il ix iy iz kk ll ncoll dtype ndyn eunit nproj mtdstp lproj iproj ntorsion prnt_dyn walker read_int cube_cv cube_only proj cube_cvmdck cube_colvar cube_full reduce is_torsion tmp smin smax dg s s1 s2 dif1 dif2 so ds w g scal maxcol mincol scal0 cube_value scoll n cv_proj dims cv_red int_tmp nthreads pfmt0 pfmt1 pfmt2 pfmt4 eunit_string econv zero
Variables
Type Attributes Name Initial
real(kind=dp) :: v
real(kind=dp) :: sp
real(kind=dp) :: la
real(kind=dp) :: vmax
real(kind=dp) :: maxw
real(kind=dp) :: minw
real(kind=dp) :: ed(5)
real(kind=dp) :: cube_tmp(6)
real(kind=dp) :: cube_rad
real(kind=dp) :: norm_proj
real(kind=dp) :: v_proj
integer :: i
integer :: j
integer :: k
integer :: l
integer :: iii
integer :: ios
integer :: il
integer :: ix
integer :: iy
integer :: iz
integer :: kk
integer :: ll
integer :: ncoll
integer :: dtype
integer :: ndyn
integer :: eunit
integer :: nproj
integer :: mtdstp
integer :: lproj
integer :: iproj
integer :: ntorsion
logical :: prnt_dyn
logical :: walker
logical :: read_int
logical :: cube_cv
logical :: cube_only
logical :: proj
logical :: cube_cvmdck
logical :: cube_colvar
logical :: cube_full
logical :: reduce
logical, ALLOCATABLE :: is_torsion(:)
real(kind=dp), ALLOCATABLE :: tmp(:)
real(kind=dp), ALLOCATABLE :: smin(:)
real(kind=dp), ALLOCATABLE :: smax(:)
real(kind=dp), ALLOCATABLE :: dg(:)
real(kind=dp), ALLOCATABLE :: s(:)
real(kind=dp), ALLOCATABLE :: s1(:)
real(kind=dp), ALLOCATABLE :: s2(:)
real(kind=dp), ALLOCATABLE :: dif1(:)
real(kind=dp), ALLOCATABLE :: dif2(:)
real(kind=dp), ALLOCATABLE :: so(:,:)
real(kind=dp), ALLOCATABLE :: ds(:)
real(kind=dp), ALLOCATABLE :: w(:)
real(kind=dp), ALLOCATABLE :: g(:)
real(kind=dp), ALLOCATABLE :: scal(:,:)
real(kind=dp), ALLOCATABLE :: maxcol(:)
real(kind=dp), ALLOCATABLE :: mincol(:)
real(kind=dp), ALLOCATABLE :: scal0(:)
real(kind=dp), ALLOCATABLE :: cube_value(:,:,:)
integer, ALLOCATABLE :: scoll(:)
integer, ALLOCATABLE :: n(:)
integer, ALLOCATABLE :: cv_proj(:)
integer, ALLOCATABLE :: dims(:)
integer, ALLOCATABLE :: cv_red(:)
integer, ALLOCATABLE :: int_tmp(:)
integer :: nthreads
character(len=80) :: pfmt0
character(len=80) :: pfmt1
character(len=80) :: pfmt2
character(len=80) :: pfmt4
character(len=8), parameter :: eunit_string(3) = (/'a.u ', 'kJ/mol ', 'kcal/mol'/)
real(kind=dp), parameter :: econv(3) = (/1.0_dp, 2625.500_dp, 627.5132632235_dp/)
real(kind=dp), parameter :: zero = 0.0_dp
All Programs
mtdrest_extract Vreco
Call graph
vreco calls get_potential, toproject
get_potential calls get_potential
toproject calls toproject